Repository BIPA-8-3/BIZSurvey_BACK, pull requests merged in 2023-12, with the labels that each got.

#79 [Refactor] : .yml change
  src/main/java/com/bipa/bizsurvey/domain/admin/api/AdminController.java
  src/main/java/com/bipa/bizsurvey/domain/user/application/UserService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: enhancement

#93 [Refactor] : ChildCommentService
  src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/ChildCommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/comment/CommentResponse.java
Labels: enhancement

#95 [Refactor] : refactor post service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java
Labels: enhancement

#99 [Refactor] : S3 Storage & workspace CRUD 리팩토링
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/ContactController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseEmitters.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Contact.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/ContactDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
Labels: Refactor

#105 [Feat] : add redis caching service
  src/main/java/com/bipa/bizsurvey/BizSurveyBackApplication.java
  src/main/java/com/bipa/bizsurvey/domain/admin/api/AdminController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityChildCommentController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityCommentController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostCount.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostTableResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
  src/main/java/com/bipa/bizsurvey/global/common/BizScheduler.java
  src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java
  src/main/java/com/bipa/bizsurvey/global/common/CustomPageImpl.java
  src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
Labels: enhancement

#107 [Feat] : 관리자 및 공유 설문 로직 수정 및 추가
  src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyCommunityController.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
  src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedListDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
  src/main/resources/application.yml
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/ContactServiceTests.java
Labels: enhancement, Refactor

#111 [Feat] : 설문지 외부 공유 및 기본형 설문지 참가 및 통계 구현
  src/main/java/com/bipa/bizsurvey/domain/survey/repository/QuestionRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedList.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurveyResponse.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyResponseDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyResponseRepository.java
Labels: enhancement, Refactor

#115 [Feat] : 외부공유 설문지 통계기능 구현
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyResponseDto.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyServiceTest.java
Labels: enhancement, Refactor

#121 Dev workspace
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
Labels: enhancement

#125 [Refactor] : 배포 프로필 backend 도메인 변경
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/resources/application.yml
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminServiceTests.java
Labels: enhancement

#129 [Chore] : build 커맨드 추가
  build.gradle
  안전보건관리비.xlsx
Labels: enhancement

#130 [Chore] : build 커맨드 추가
  build.gradle
  안전보건관리비.xlsx
Labels: enhancement

#137 [Refactor] : refactor vote service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionType.java
Labels: enhancement

#139 [Chore] : prod profile 수정
  src/main/resources/application.yml
Labels: enhancement

#140 prod profile 수정
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionType.java
  src/main/resources/application.yml
Labels: enhancement

#141 [Refactor] : refactor vote service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/AnswerPercentageResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/VoteRepository.java
Labels: enhancement

#142 [Feat] : test
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityChildCommentController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityCommentController.java
Labels: enhancement

#145 Dev
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityChildCommentController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityCommentController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/AnswerPercentageResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/VoteRepository.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/user/dto/PasswordUpdateRequest.java
  src/main/java/com/bipa/bizsurvey/global/config/SecurityConfig.java
Labels: enhancement

#146 Update UtilController.java
  src/main/java/com/bipa/bizsurvey/global/util/UtilController.java
Labels: enhancement

#147 Dev
  src/main/java/com/bipa/bizsurvey/global/util/UtilController.java
Labels: enhancement

#148 [Chore] : 배포 프로파일 변경
  src/main/resources/application.yml
Labels: enhancement

#149 [Refactor] : 메일 이미지 수정
  src/main/java/com/bipa/bizsurvey/global/common/email/MailUtil.java
Labels: enhancement

#150 [Refactor] : refactor post detail
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/ChildCommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/childComment/ChildCommentResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/comment/CommentResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java
Labels: enhancement

#152 Dev
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/ChildCommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/childComment/ChildCommentResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/comment/CommentResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java
  src/main/java/com/bipa/bizsurvey/domain/user/application/EmailSendService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/resources/application.yml
Labels: enhancement

#155 [Refactor] : infra 깨진 파일 수정
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/request/UploadSurveyFileDto.java
  src/main/java/com/bipa/bizsurvey/infra/s3/AwsS3Service.java
  src/main/java/com/bipa/bizsurvey/infra/s3/FileUtil.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Controller.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Domain.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Folder.java
  src/main/java/com/bipa/bizsurvey/infra/s3/ShareType.java
Labels: enhancement

#157 [Feat] : redis 비밀번호 추가 & 워크스페이스 접근 권한 수정
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: enhancement

#158 [Feat] : redis 비밀번호 추가 & 워크스페이스 접근 권한 수정
  src/main/java/com/bipa/bizsurvey/domain/admin/application/AdminCommunityService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/request/UploadSurveyFileDto.java
  src/main/java/com/bipa/bizsurvey/domain/user/application/UserService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java
  src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
  src/main/java/com/bipa/bizsurvey/infra/s3/AwsS3Service.java
  src/main/java/com/bipa/bizsurvey/infra/s3/FileUtil.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Controller.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Domain.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Folder.java
  src/main/java/com/bipa/bizsurvey/infra/s3/ShareType.java
  src/main/resources/application.yml
Labels: enhancement

#159 [Refactor] refactor community post
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
Labels: enhancement

#162 [Feat] : S3 여러파일 삭제 컨트롤러 추가 && workspace 권한 추가
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/DeleteFileRequest.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceServiceTests.java
Labels: enhancement

#164 [Feat] : S3 임시저장 파일 확정 메소드 추가
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/TemporaryFileConfirmRequest.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
Labels: enhancement

#165 [Feat] : refactor SurveyPost service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/CreatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostCardResponse.java
Labels: enhancement

#168 [Refactor] : 워크스페이스 권한 수정
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
Labels: enhancement

#169 [Refactor] : refactor post service
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
Labels: enhancement

#171 [Refactor] : 개별응답 변경
  src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
Labels: enhancement

#174 [Feat] : 마감기한 추가 & 파일 업로드 용량 설정
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
  src/main/resources/application.yml
Labels: enhancement

#175 [Fixs] : 1차 버그 수정 배포
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostImageService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/CreatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostCardResponse.java
  src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Answer.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/UserSurveyResponse.java
  src/main/java/com/bipa/bizsurvey/domain/user/api/OAuth2Controller.java
  src/main/java/com/bipa/bizsurvey/domain/user/application/UserService.java
  src/main/java/com/bipa/bizsurvey/domain/user/dto/PasswordUpdateRequest.java
  src/main/java/com/bipa/bizsurvey/domain/user/dto/mypage/UserInfoResponse.java
  src/main/java/com/bipa/bizsurvey/domain/user/exception/UserExceptionType.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/DeleteFileRequest.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/TemporaryFileConfirmRequest.java
  src/main/java/com/bipa/bizsurvey/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceServiceTests.java
Labels: enhancement

#176 [Refactor] : 설문 question, answer column수정
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Answer.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Question.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
Labels: enhancement

#177 [Refactor] : 설문 column수정
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Answer.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Question.java
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
Labels: enhancement

#178 [Refactor] : invite entity & repository 제거
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Invite.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/InviteRepository.java
Labels: enhancement

#179 [Refactor] : 워크스페이스 entity 수정
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Contact.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Workspace.java
Labels: enhancement

#183 [Refactor] : 설문 정렬 수정
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/request/UpdateSurveyRequest.java
Labels: enhancement

#184 [Refacor] : 통합 배포
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/resources/application.yml
Labels: enhancement

#185 [Refacor] : 통합 배포
  src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/request/UpdateSurveyRequest.java
  src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/user/api/OAuth2Controller.java
  src/main/java/com/bipa/bizsurvey/domain/user/exception/UserExceptionType.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/resources/application.yml
Labels: enhancement

#187 [Fix] : 점수 설문 순서 정렬
  src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/ScoreResultResponse.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
Labels: bug

#188 [Refactor] : SSE, console 제거
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseEmitters.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
Labels: enhancement

#189 [Refactor] : sse 제거, console 제거
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseEmitters.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
Labels: enhancement

#190 [Refactor] : 링크 검증 메세지 수정
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
Labels: enhancement

#191 [Refactor] : 링크 검증 메세지 수정
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
Labels: enhancement
