Repository BIPA-8-3/BIZSurvey_BACK, pull requests merged in 2023-11, with the labels that each got.

#5 [Feat] : Add redis config, Qdsl config
  build.gradle
  src/main/java/com/bipa/bizsurvey/domain/voteUserAnswer/domain/VoteUserAnswer.java
  src/main/java/com/bipa/bizsurvey/global/config/QueryDslConfig.java
  src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: enhancement

#8 [Feat] : Add ValidationExceptionHandler, ErrorDto, ErrorCode
  src/main/java/com/bipa/bizsurvey/global/error/ErrorCode.java
  src/main/java/com/bipa/bizsurvey/global/error/ErrorDto.java
  src/main/java/com/bipa/bizsurvey/global/exceptionHandler/ValidationExceptionHandler.java
Labels: enhancement

#9 [Feat] : Add security config
  build.gradle
  src/main/java/com/bipa/bizsurvey/global/config/SecurityConfig.java
Labels: enhancement

#12 [Refactor] : Exception Handling 방법 변경
  src/main/java/com/bipa/bizsurvey/domain/post/postException/PostException.java
  src/main/java/com/bipa/bizsurvey/domain/post/postException/PostExceptionHandler.java
  src/main/java/com/bipa/bizsurvey/domain/post/postException/PostExceptionType.java
  src/main/java/com/bipa/bizsurvey/global/error/ErrorCode.java
  src/main/java/com/bipa/bizsurvey/global/error/ErrorDto.java
  src/main/java/com/bipa/bizsurvey/global/exception/BaseException.java
  src/main/java/com/bipa/bizsurvey/global/exception/BaseExceptionType.java
  src/main/java/com/bipa/bizsurvey/global/exception/ExceptionDto.java
  src/main/java/com/bipa/bizsurvey/global/exceptionHandler/ValidationExceptionHandler.java
Labels: bug

#22 [Feat] : Post Create 서비스 제작
  build.gradle
  src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/CreatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/user/repository/UserRepository.java
  src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java
  src/test/java/com/bipa/bizsurvey/domain/community/service/PostServiceTest.java
Labels: enhancement

#24 [Feat] : add RedisService
  src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
Labels: enhancement

#27 [Feat] : Post 조회 기능 추가
  build.gradle
  src/main/java/com/bipa/bizsurvey/BizSurveyBackApplication.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/PostResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/global/common/BizScheduler.java
  src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java
Labels: enhancement

#34 [Feat] : post service 수정 삭제 검색 제작
  src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/CreatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/SearchPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/UpdatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/postException/PostExceptionHandler.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/postException/PostExceptionType.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/user/exception/UserExceptionType.java
  src/main/java/com/bipa/bizsurvey/global/common/BaseEntity.java
  src/main/java/com/bipa/bizsurvey/global/exceptionHandler/ValidationExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java
  src/test/java/com/bipa/bizsurvey/domain/community/service/PostServiceTest.java
Labels: enhancement

#39 Dev infra
  build.gradle
  src/main/java/com/bipa/bizsurvey/infra/s3/AwsS3Service.java
  src/main/java/com/bipa/bizsurvey/infra/s3/FileUtil.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Config.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Controller.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Domain.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Folder.java
  src/main/java/com/bipa/bizsurvey/infra/s3/ShareType.java
  src/main/java/com/bipa/bizsurvey/infra/s3/UploadSurveyFileDto.java
  src/main/resources/application.yml
  src/test/java/com/bipa/bizsurvey/infra/s3/AwsS3ServiceTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#52 [Feat] : S3 종속성 제거, StorageController, StorageService, S3StorageService, DTO 추가 구현 및 코드 리팩토링
  src/main/java/com/bipa/bizsurvey/global/common/storage/Domain.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/FileUtil.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/Folder.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/ShareType.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/UploadRequest.java
  src/main/java/com/bipa/bizsurvey/global/common/storage/UploadSurveyAnswerRequest.java
  src/main/java/com/bipa/bizsurvey/infra/s3/AwsS3Service.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Config.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3Controller.java
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageService.java
  src/test/java/com/bipa/bizsurvey/infra/s3/AwsS3ServiceTest.java
Labels: enhancement, Refactor

#56 Dev infra
  src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
Labels: Refactor

#61 [Feat] : Add vote service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Vote.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/VoteAnswer.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/VoteUserAnswer.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/request/CreateVoteAnswerRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/request/CreateVoteRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/request/CreateVoteUserAnswerRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/response/AnswerPercentageResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/response/VoteAnswerResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteException.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionHandler.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionType.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/VoteAnswerRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/VoteRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/VoteUserAnswerRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/ChildCommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/CommentService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/VoteService.java
  src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingRequest.java
  src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingService.java
  src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingStandard.java
Labels: enhancement

#66 [Feat] : Add SurveyPost Service
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
  src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteAnswerRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteUserAnswerRequest.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/AnswerPercentageResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteAnswerResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostException.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostExceptionHandler.java
  src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostExceptionType.java
  src/main/java/com/bipa/bizsurvey/domain/community/repository/PostImagesRepository.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/VoteService.java
  src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/user/domain/User.java
Labels: enhancement

#67 [Feat] : Add score service
  src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
  src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
  src/main/java/com/bipa/bizsurvey/domain/community/enums/AccessType.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/SurveyPostService.java
Labels: enhancement

#73 [Feat] : 검색 자동 완성 기능 추가
  src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
  src/main/java/com/bipa/bizsurvey/domain/community/service/SurveyPostService.java
  src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java
Labels: enhancement

#75 [Feat] : Workspace 도메인 구현
  build.gradle
  src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
  src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/FileInfo.java
  src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/ContactController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Contact.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedList.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurveyResponse.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Workspace.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/ContactDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/PageRequestDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedListDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyResponseDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceDto.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/mq/ExpirationListener.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/mq/Publisher.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/mq/RedisListenerConfig.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/mq/RedisPublisherConfig.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/ContactRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/InviteRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedListRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyResponseRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
  src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
  src/main/java/com/bipa/bizsurvey/global/common/BaseEntity.java
  src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
  src/main/java/com/bipa/bizsurvey/global/common/email/EmailMessage.java
  src/main/java/com/bipa/bizsurvey/global/common/email/MailUtil.java
  src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
  src/main/java/com/bipa/bizsurvey/global/config/ThymeleafConfig.java
  src/main/resources/application.yml
  src/main/resources/static/img/logo.png
  src/main/resources/templates/mail/mail.html
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/ContactServiceTests.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyServiceTest.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminServiceTests.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceServiceTests.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/repository/ContactRepositoryTests.java
  src/test/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepositoryTests.java
  src/test/java/com/bipa/bizsurvey/global/config/TestConfig.java
  src/test/java/com/bipa/bizsurvey/infra/mail/MailTest.java
Labels: enhancement
